<?php

/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use JMS\Serializer\Serializer;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;

interface StoreApiServiceInterface
{

    /**
     * Operation getInventory
     *
     * Returns pet inventories by status.
     *
     * @param array $inputData Associative array containing the input data
     *
     * @return OutputData 
     */
    public function getInventory(array $inputData);
        
    /**
     * Operation placeOrder
     *
     * Place an order for a pet.
     *
     * @param array $inputData Associative array containing the input data
     *
     * @return OutputData 
     */
    public function placeOrder(array $inputData);
        
    /**
     * Operation deleteOrder
     *
     * Delete purchase order by ID.
     *
     * @param array $inputData Associative array containing the input data
     *
     * @return OutputData 
     */
    public function deleteOrder(array $inputData);
        
    /**
     * Operation getOrderById
     *
     * Find purchase order by ID.
     *
     * @param array $inputData Associative array containing the input data
     *
     * @return OutputData 
     */
    public function getOrderById(array $inputData);
        

}
