<?php

/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace Controllers;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use JMS\Serializer\Serializer;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
// Need proper path to the ServiceInterface...
use StoreApiServiceInterface;


class StoreApi
{
    private $StoreService;
    private $validator;
    private $serializer;

    public function setStoreService(StoreApiServiceInterface $service)
    {
        $this->StoreService = $service;
    }

    public function setValidator(ValidatorInterface $validator)
    {
        $this->validator = $validator;
    }

    public function setSerializer(Serializer $serializer)
    {
        $this->serializer = $serializer;
    }

    /**
     * Operation getInventory
     * Returns pet inventories by status.
     *
     * @return map[string,int]
     */
    public function getInventory(Request $request)
    {
        $inputData = [];

        // Call business logic with input data array.
        $output = $this->StoreApiService->getInventory($inputData);

        $validResponses = [];

        $assertsOutput = [];


        $validResponses['200'] = [
            'message'   => 'successful operation',
            'assertsOutput'  => $assertsOutput
        ];

        if (isset($validResponses[$output->responseCode])) {
            // Get the response type indicated by the business logic
            $response = $validResponses[$output->responseCode];
        } elseif (isset($validResponses['default'])) {
            $response = $validResponses['default'];
        } else {
            // We don't recognize this reponse type from the spec
            return new Response($output->data, $output->responseCode);
        }

        // Check if we have a schema defined for the response type
        if (!empty($response['assertsOutput'])) {
            // Validate response type
            $this->validateData($output->data, $response['assertsOutput']);
        }

        // Determine what to return as the response
        if (!empty($output->data)) {
            $responseData = $this->produceOutput($request, $output->data);
        } else {
            $responseData = $response['message'];
        }

        // Return response
        return new Response($responseData, $output->responseCode);
    }
    /**
     * Operation placeOrder
     * Place an order for a pet.
     *
     * @return \Model\Order
     */
    public function placeOrder(Request $request)
    {
        $inputData = [];
        // Unwrap parameter value
        $inputData['body'] = $request->request->get('body');

        $asserts = [];

        $asserts[] = new Assert\Type("\Model\Order");

        // Validate input parameter
        $this->validateData($inputData['body'], $asserts);


        // Call business logic with input data array.
        $output = $this->StoreApiService->placeOrder($inputData);

        $validResponses = [];

        $assertsOutput = [];


        $validResponses['200'] = [
            'message'   => 'successful operation',
            'assertsOutput'  => $assertsOutput
        ];


        $validResponses['400'] = [
            'message'   => 'Invalid Order',
            'assertsOutput'  => $assertsOutput
        ];

        if (isset($validResponses[$output->responseCode])) {
            // Get the response type indicated by the business logic
            $response = $validResponses[$output->responseCode];
        } elseif (isset($validResponses['default'])) {
            $response = $validResponses['default'];
        } else {
            // We don't recognize this reponse type from the spec
            return new Response($output->data, $output->responseCode);
        }

        // Check if we have a schema defined for the response type
        if (!empty($response['assertsOutput'])) {
            // Validate response type
            $this->validateData($output->data, $response['assertsOutput']);
        }

        // Determine what to return as the response
        if (!empty($output->data)) {
            $responseData = $this->produceOutput($request, $output->data);
        } else {
            $responseData = $response['message'];
        }

        // Return response
        return new Response($responseData, $output->responseCode);
    }
    /**
     * Operation deleteOrder
     * Delete purchase order by ID.
     *
     * @param int $order_id ID of the order that needs to be deleted (required)
     */
    public function deleteOrder(Request $request, $order_id)
    {
        $inputData = [];
        // Unwrap parameter value
        $inputData['order_id'] = $order_id;

        $asserts = [];

        $asserts[] = new Assert\Type("long");
        $asserts[] = new Assert\GreaterThanOrEqual(1);

        // Validate input parameter
        $this->validateData($inputData['order_id'], $asserts);


        // Call business logic with input data array.
        $output = $this->StoreApiService->deleteOrder($inputData);

        $validResponses = [];

        $assertsOutput = [];


        $validResponses['400'] = [
            'message'   => 'Invalid ID supplied',
            'assertsOutput'  => $assertsOutput
        ];


        $validResponses['404'] = [
            'message'   => 'Order not found',
            'assertsOutput'  => $assertsOutput
        ];

        if (isset($validResponses[$output->responseCode])) {
            // Get the response type indicated by the business logic
            $response = $validResponses[$output->responseCode];
        } elseif (isset($validResponses['default'])) {
            $response = $validResponses['default'];
        } else {
            // We don't recognize this reponse type from the spec
            return new Response($output->data, $output->responseCode);
        }

        // Check if we have a schema defined for the response type
        if (!empty($response['assertsOutput'])) {
            // Validate response type
            $this->validateData($output->data, $response['assertsOutput']);
        }

        // Determine what to return as the response
        if (!empty($output->data)) {
            $responseData = $this->produceOutput($request, $output->data);
        } else {
            $responseData = $response['message'];
        }

        // Return response
        return new Response($responseData, $output->responseCode);
    }
    /**
     * Operation getOrderById
     * Find purchase order by ID.
     *
     * @param int $order_id ID of pet that needs to be fetched (required)
     * @return \Model\Order
     */
    public function getOrderById(Request $request, $order_id)
    {
        $inputData = [];
        // Unwrap parameter value
        $inputData['order_id'] = $order_id;

        $asserts = [];

        $asserts[] = new Assert\Type("long");
        $asserts[] = new Assert\GreaterThanOrEqual(1);
        $asserts[] = new Assert\LessThanOrEqual(1);

        // Validate input parameter
        $this->validateData($inputData['order_id'], $asserts);


        // Call business logic with input data array.
        $output = $this->StoreApiService->getOrderById($inputData);

        $validResponses = [];

        $assertsOutput = [];


        $validResponses['200'] = [
            'message'   => 'successful operation',
            'assertsOutput'  => $assertsOutput
        ];


        $validResponses['400'] = [
            'message'   => 'Invalid ID supplied',
            'assertsOutput'  => $assertsOutput
        ];


        $validResponses['404'] = [
            'message'   => 'Order not found',
            'assertsOutput'  => $assertsOutput
        ];

        if (isset($validResponses[$output->responseCode])) {
            // Get the response type indicated by the business logic
            $response = $validResponses[$output->responseCode];
        } elseif (isset($validResponses['default'])) {
            $response = $validResponses['default'];
        } else {
            // We don't recognize this reponse type from the spec
            return new Response($output->data, $output->responseCode);
        }

        // Check if we have a schema defined for the response type
        if (!empty($response['assertsOutput'])) {
            // Validate response type
            $this->validateData($output->data, $response['assertsOutput']);
        }

        // Determine what to return as the response
        if (!empty($output->data)) {
            $responseData = $this->produceOutput($request, $output->data);
        } else {
            $responseData = $response['message'];
        }

        // Return response
        return new Response($responseData, $output->responseCode);
    }

    private function validateData($data, $asserts)
    {
        $errors = $this->validator->validate($data, $asserts);

        if (count($errors) > 0) {
            $errorsString = (string)$errors;
            throw new BadRequestHttpException($errorsString);
        }
    }

    private function produceOutput(Request $request, $output)
    {
        $accept = $request->headers->has('accept')?$request->headers->get('accept'):'application/json';
        switch ($accept) {
            case 'application/json':
                return $this->serializer->serialize($output, 'json');
            case 'application/xml':
                return $this->serializer->serialize($output, 'xml');
            default:
                throw new BadRequestHttpException('Unsupported return format requested');
        }
    }
}
